name: Stas-CICD

env: 
  APPLICATION_NAME: "MY_PAIN"

on: 
  push:
    branches: 
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
    - name: Set PACKAGE_NAME
      run: echo "PACKAGE_NAME=deploy-ver-${{ github.sha }}" >> $GITHUB_ENV
    - name: Run a one-line script
      run: echo "Hello, world! From Test"
    - name: Run a multi-line script
      run: |
        echo "Add other actions to build,"
        echo "test a multi-line project."
    - name: Execute few commands
      run: |
        echo "This is string 1"
        echo "Next job has ${{ env.PACKAGE_NAME }}"
        
  my_LoL:
    runs-on: ubuntu-latest
    steps:
    - name: This is only for traing
      run : ls -la
    - name: THis for ander how worr uses  
    - uses: actions/checkout@v1
    - name: Next step
      run : ls -la

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_test]
    steps:
    - name: Print Hello World
      run: echo "Hello World! From Deploy"
    - name: Execute few commands
      run: |
        echo "This is string 1"
        echo "Hello ${{ env.APPLICATION_NAME }}"
