# This my first CI/CD in GitHub

name: Stas-CICD

env: 
  APPLICATION_NAME: "MY_PAIN"
  PACKEGA_NAME    : "deploy-ver-${{ github.sha }}"
  

on: 
  push:
    branches: 
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: "echo Hellp, world! From Test"
    - name: Run a mulri-line script
      run: 
        echo "Add other actions to build,"
        echo "test a mulri-line project."
    - name: Execre few commands
      run : |
        echo "This is string 1"
        echo "Next job have ${{ env.PACKEGA_NAME }}
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_test]
    steps:
      - name: Print Hello World
        run : echo "Hello World! From Deploy"
      - name: Execre few commands
        run : |
          echo "This is string 1"
          echo "Hello ${{ env.APPLICATION_NAME }}
