name: Stas-CICD

env: 
  APPLICATION_NAME: "MY_PAIN"

on: 
  push:
    branches: 
      - main

jobs:
  my_test:
    runs-on: ubuntu-latest
    env:
      VAR1: "This is job level variable"
    steps:
    - name: Set PACKAGE_NAME
      run: echo "PACKAGE_NAME=deploy-ver-${{ github.sha }}" >> $GITHUB_ENV
    - name: Run a one-line script
      run: echo "Hello, world! From Test"
    - name: Run a multi-line script
      run: |
        echo "Add other actions to build,"
        echo "test a multi-line project."
    - name: This is var
      run: |
        echo "Var is ${{ env.VAR1 }}"
        echo "Var2 is $Local_VAR"
      env:
        Local_VAR: "123"

  my_LoL:
    runs-on: ubuntu-latest
    steps:
    - name: This is only for training
      run: ls -la
    - name: Understanding how actions work
      run: echo "Checking how GitHub Actions works"
    - uses: actions/checkout@v4
    - name: Next step
      run: ls -la

  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_test]
    steps:
    - name: Print Hello World
      run: echo "Hello World! From Deploy"
    - name: Execute few commands
      run: |
        echo "This is string 1"
        echo "Hello ${{ env.APPLICATION_NAME }}"
    - name: Do we have azure?
      run: azure --version
